// Default configuration - can be overridden by user settings
export const DEFAULT_CONFIG = {
  TARGET_FORM_SELECTOR: "#upload_table",
  SUBMIT_KEYBINDING: true,
  CUSTOM_SUBMIT_KEYBINDING: "Ctrl+Enter",
  APPLY_KEYBINDING: true,
  CUSTOM_APPLY_KEYBINDING: "Alt+A",
  HELP_KEYBINDING: true,
  CUSTOM_HELP_KEYBINDING: "Shift+?",
  CUSTOM_FIELD_SELECTORS: [],
  IGNORED_FIELDS_BY_DEFAULT: [
    "linkgroup",
    "groupid",
    "apikey",
    "type",
    "amazonuri",
    "googleplaybooksuri",
    "goodreadsuri",
    "isbn",
    "scan_dpi",
    "other_dpi",
    "release_desc",
    "anonymous",
    "dont_check_rules",
    "title",
    "tags",
    "image",
    "gameswebsiteuri",
    "wikipediauri",
    "album_desc",
    "submit_upload",
  ],
};
